version: 3

tasks:
  dev:
    cmd: ./bin/dev
    desc: Serve rails app

  test:
    cmd: ./bin/rails test
    desc: Test rails app

  format:
    cmd: erb-format app/views/**/*.html.erb --write
    desc: Format ERB code
