development:
  adapter: postgresql
  encoding: unicode
  database: goldroger
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: goldroger_test
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  port: 5432
